#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:admin}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:America/Sao_Paulo}}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DB_HOST:192.168.2.216}:${DB_PORT:3306}/${DB_NAME:admin}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${DB_TIMEZONE:America/Sao_Paulo}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${DB_USER:SoftwareSignAPI}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${DB_PASS:Software@9fK72qLm!}}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:${DB_DDL_AUTO:update}}
server.port=${SERVER_PORT:1700}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.apache.pdfbox=ERROR
logging.level.org.apache.pdfbox.pdmodel.font=ERROR
logging.level.org.apache.pdfbox.pdmodel=ERROR
logging.level.org.apache.fontbox=ERROR

# Configurações do Sistema de Assinatura
app.signature.internal-notification-timeout-hours=48
app.signature.confirmation-email.enabled=true
app.signature.confirmation-email.from=ricardo@software.com.br
CLICKSIGN_API_KEY_SOFTWARE=ebd710ae-b25d-40b4-9802-15d3ef98a703
CLICKSIGN_API_KEY_OTHER=061274f1-91ee-40a4-8c06-8035ac60b42f

# URL PROD
CLICKSIGN_BASE_URL=https://app.clicksign.com/api/v3
# URLs para Webhook ClickSign (configurar no painel ClickSign)
app.webhook.clicksign.url=https://app.clicksign.com/api/v3

# Envio: notificação assíncrona para reduzir latência da resposta
app.send.notify-async=true
